### PR TITLE
Firebaseimp

### LINKED ISSUE #23: Add Firebase code for user login/ logout/ register account
https://firebase.google.com/docs/auth/android/start
https://firebase.google.com/docs/auth/android/password-auth?authuser=0
I have the login screen, but still figuring out how to get it working with the database :)

### LINKED ISSUE #25: Fix the login screen (per class suggestions)
separate create account and log into account screens.

### PR DESCRIPTION
**Pull request by horinet**
Fixed the login/create screens. Added functionality to the buttons (Worked on Tuesday during the PODs, but not when I presented today), Started digging into the firebase class that I added via the tutorial. Finished my reflection!

### CODE REVIEW

**Comment by horinet** [comment]
Hi Imma. It is like a list of 100+ errors when I attempt to run the addtask.java file with the firebase implementation. Something about a "hidden method" and Google did not help me figure out quite what that was. However, I did figure out how to add name and email to the database with a collection and document via firestore, but no luck with the task. I followed the same set up as the code in register.java class with this video/playlist series that you showed me https://youtu.be/RiHGwJ_u27k.

**Comment by horinet** [comment]
I am ready to merge this to the main branch. What it currently does: logs in. logs out users, creates accounts: stores the name and email they have input into the app when registering account. Stores the task data from the add task screen, but does not create a new map of data to put in firebase, only edits the one already put in there.

**Comment by horinet** [comment]
I need this to be approved to be merged before I can merge fbtasks&tdscreen branch to main.

**Comment by jazzij** [comment]
Approved!

**Pull request merged**
